routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/home');

Auth::routes([
    'register' => false,
    'verify' => false,
]);

Route::middleware(['auth', 'manager'])->group(function () {
    Route::resource('users', 'UserController')->except(['show']);
    Route::resource('cars', 'CarController');

    Route::get('admin', function () {
        return view('admin.panel');
    });
});

Route::middleware(['auth'])->group(function () {
    Route::resource('home', 'HomeController');
});

app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    public function bookings()
    {
        return $this->hasMany('App\Booking');
    }

    public function maintenances()
    {
        return $this->hasMany('App\Maintenance');
    }

    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }
}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use App\Car;
use Illuminate\Http\Request;
use App\Http\Requests\CarRequest;
use App\Http\Requests\CarEditRequest;
use Illuminate\Support\Facades\Storage;

class CarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cars = Car::all();

        return view('admin.cars.index', compact('cars'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.cars.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CarRequest $request)
    {
        $car = new Car();

        $car->brand = request('brand');
        $car->model = request('model');
        $car->license_plate = request('license_plate');
        $car->photo = request()->file('photo')->store('cars', 'public');
        $car->registration_certificate = request()->file('registration_certificate')->store('certificates', 'public');
        $car->save();

        return redirect()->route('cars.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Car $car)
    {
        return view('admin.cars.edit', compact('car'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(CarEditRequest $request, Car $car)
    {
        $car->brand = request('brand');
        $car->model = request('model');
        $car->license_plate = request('license_plate');

        if ($request->has('photo')) {
            Storage::disk('public')->delete($car->photo);

            $car->photo = request()->file('photo')->store('cars', 'public');
        }

        if ($request->has('registration_certificate')) {
            Storage::disk('public')->delete($car->registration_certificate);

            $car->registration_certificate = request()->file('registration_certificate')->store('certificates', 'public');
        }

        $car->save();

        return redirect()->route('cars.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Car $car)
    {
        Storage::disk('public')->delete($car->photo);
        Storage::disk('public')->delete($car->registration_certificate);

        $car->delete();

        return back();
    }
}

resources/views/admin/cars/create.blade.php
@extends('layouts.card')
@section('card-header', 'Create car')
@section('card')
    <form method="POST" enctype="multipart/form-data" action={{route('cars.store')}}>
        @csrf
        @method('POST')

        <div class="form-group row">
            <label for="brand" class="col-md-4 col-form-label text-md-right">{{ __('Brand') }}</label>

            <div class="col-md-6">
                <input id="brand" type="text"
                       class="form-control @error('brand') is-invalid @enderror" name="brand"
                       value="{{ old('brand') }}" autocomplete="brand" autofocus>
            </div>
        </div>

        <div class="form-group row">
            <label for="model"
                   class="col-md-4 col-form-label text-md-right">{{ __('Model') }}
            </label>
            <div class="col-md-6">
                <input id="model" type="text"
                       class="form-control @error('model') is-invalid @enderror"
                       name="model" value="{{ old('model') }}" autocomplete="model">
            </div>
        </div>

        <div class="form-group row">
            <label for="license_plate"
                   class="col-md-4 col-form-label text-md-right">{{ __('License Plate') }}
            </label>
            <div class="col-md-6">
                <input id="license_plate" type="text"
                       class="form-control @error('license_plate') is-invalid @enderror"
                       name="license_plate" value="{{ old('license_plate') }}" autocomplete="license_plate">
            </div>
        </div>

        <div class="form-group row">
            <label for="photo"
                   class="col-md-4 col-form-label text-md-right">{{ __('Photo') }}
            </label>
            <div class="col-md-6">
                <input id="photo" type="file"
                       class="form-control @error('photo') is-invalid @enderror"
                       name="photo" value="{{ old('photo') }}">
            </div>
        </div>

        <div class="form-group row">
            <label for="registration_certificate"
                   class="col-md-4 col-form-label text-md-right">{{ __('Registration Certificate') }}
            </label>
            <div class="col-md-6">
                <input id="registration_certificate" type="file"
                       class="form-control @error('registration_certificate') is-invalid @enderror"
                       name="registration_certificate" value="{{ old('registration_certificate') }}">
            </div>
        </div>

        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    {{ __('Create car') }}
                </button>
                <a href="{{route('cars.index')}}" class="btn btn-danger">Cancel</a>
            </div>
        </div>
    </form>
@endsection

resources/views/admin/cars/edit.blade.php
@extends('layouts.card')
@section('card-header', 'Edit car')
@section('card')

    <form method="POST" enctype="multipart/form-data" action="{{route('cars.update',[$car->id])}}">
        @csrf
        @method('PUT')
        <div class="form-group row">
            <label for="created" class="col-md-4 col-form-label text-md-right">Created at :</label>
            <label for="created"
                   class="col-md-4 col-form-label text-md-right">{{ $car->created_at->format('d-m-y H:i:s')}}</label>
        </div>

        <div class="form-group row">
            <label for="brand" class="col-md-4 col-form-label text-md-right">{{ __('Brand') }}</label>

            <div class="col-md-6">
                <input id="brand" type="text"
                       class="form-control @error('brand') is-invalid @enderror" name="brand"
                       value="{{ $car->brand }}" autocomplete="brand" autofocus>
            </div>
        </div>

        <div class="form-group row">
            <label for="model"
                   class="col-md-4 col-form-label text-md-right">{{ __('Model') }}
            </label>
            <div class="col-md-6">
                <input id="model" type="text"
                       class="form-control @error('model') is-invalid @enderror"
                       name="model" value="{{ $car->model }}" autocomplete="model">
            </div>
        </div>

        <div class="form-group row">
            <label for="license_plate"
                   class="col-md-4 col-form-label text-md-right">{{ __('License Plate') }}
            </label>
            <div class="col-md-6">
                <input id="license_plate" type="text"
                       class="form-control @error('license_plate') is-invalid @enderror"
                       name="license_plate" value="{{ $car->license_plate }}" autocomplete="license_plate">
            </div>
        </div>

        <div class="form-group row">
            <label for="photo"
                   class="col-md-4 col-form-label text-md-right">{{ __('Photo') }}
            </label>
            <div class="col-md-6">
                <input id="photo" type="file"
                       class="form-control @error('photo') is-invalid @enderror"
                       name="photo" value="{{ $car->photo }}">
                <img class="picture" src="{{asset('storage/'.$car->photo) }}"/>

            </div>
        </div>

        <div class="form-group row">
            <label for="registration_certificate"
                   class="col-md-4 col-form-label text-md-right">{{ __('Registration Certificate') }}
            </label>
            <div class="col-md-6">
                <input id="registration_certificate" type="file"
                       class="form-control @error('registration_certificate') is-invalid @enderror"
                       name="registration_certificate" value="{{ $car->registration_certificate }}">
                <img class="picture" src="{{asset('storage/'.$car->registration_certificate) }}"/>

            </div>
        </div>


        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    {{ __('Save') }}
                </button>
                <a href="{{route('cars.index')}}" class="btn btn-danger">Cancel</a>
            </div>
        </div>
    </form>
@endsection

resources/views/admin/cars/index.blade.php
@extends('layouts.card')
@section('card-header')
    Car panel
    <div class="float-right"><a href="{{route('cars.create')}}">Create car</a></div>
@endsection
@section('card')

    <table id="car-table">
        <thead>
        <tr>
            <th id="brand">Brand</th>
            <th id="model">Model</th>
            <th id="license-plate">Plate no.</th>
            <th id="photo">Photo</th>
            <th id="registration-certificate">Certificate</th>
            <th id="adjust">Adjust</th>
            <th id="delete">Delete</th>

        </tr>
        </thead>

        <tbody>
        @foreach ($cars as $car)
            <tr>
                <td>{{ $car->brand }}</td>
                <td>{{ $car->model }}</td>
                <td>{{ $car->license_plate }}</td>
                <td><a href="{{asset('storage/'.$car->photo) }}"> Photo</a> </td>
                <td><a href="{{asset('storage/'.$car->registration_certificate) }}">Certificate</a> </td>

                <td>
                    <a href="{{route('cars.edit',[$car->id])}}" class="btn btn-secondary">
                        <i class="far fa-edit"> </i>
                    </a>
                </td>
                <td>
                    <form action="{{route('cars.destroy',[$car->id])}}" method="POST">
                        @csrf @method('DELETE')
                        <button id="delete" type="submit" class="btn btn-danger"
                                onclick="return confirm('Do you really want to delete this car?');">
                            <i class="far fa-trash-alt"> </i>
                        </button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    <script>
        $(document).ready(function () {
            $('#car-table').DataTable();
        });
    </script>

@endsection